# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research & Projects
    url: project
    weight: 10
  - name: Data & code
    url: https://github.com/geco-bern
    weight: 20
  - name: Courses
    url: teaching
    identifier: courses
    weight: 30
  - name: Applied Geodata Science I
    url: https://geco-bern.github.io/agds/
    parent: courses
  - name: Applied Geodata Science II
    url: https://geco-bern.github.io/agds2_course/
    parent: courses
  - name: Proseminar in Geocomputation and Earth Observation
    url: https://geco-bern.github.io/agds_proseminar/
    parent: courses
  - name: Tutorials
    url: tutorials
    identifier: tutorials
    weight: 40
  - name: Applied Geodata Science
    url: https://geco-bern.github.io/agds_book/
    parent: tutorials
    weight: 41
  - name: Land in the Earth System
    url: https://geco-bern.github.io/les/
    parent: tutorials
    weight: 42
  - name: A Handful of Pixels - Phenology modelling and land cover classification
    url: https://geco-bern.github.io/handfull_of_pixels/
    parent: tutorials
    weight: 43
  - name: Digital Soil Mapping
    url: https://geco-bern.github.io/tutorial_digital_soil_mapping/
    parent: tutorials
    weight: 44
  - name: Leaf Energy Balance
    url: https://padasch.github.io/leaf_energy_balance_tutorial/
    parent: tutorials
    weight: 45
  - name: Machine learning for Eddy Covariance data
    url: https://geco-bern.github.io/ml4ec_workshop/
    parent: tutorials
    weight: 46
  - name: Blog
    url: post
    weight: 50
  - name: People
    url: people
    weight: 60
  - name: Join us
    url: joinus
    weight: 70
  - name: Publications
    url: publication
    weight: 80
  - name: Contact
    url: contact
    weight: 90
